ares.components += mos6502

ares.objects += ares-base6502-system
ares.objects += ares-base6502-cartridge
ares.objects += ares-base6502-cpu
ares.objects += ares-base6502-ppu

$(object.path)/ares-base6502-system.o:     $(ares.path)/base6502/system/system.cpp
$(object.path)/ares-base6502-cartridge.o:  $(ares.path)/base6502/cartridge/cartridge.cpp
$(object.path)/ares-base6502-cpu.o:        $(ares.path)/base6502/cpu/cpu.cpp
$(object.path)/ares-base6502-ppu.o:        $(ares.path)/base6502/ppu/ppu.cpp
