auto S1C88::disassembleFetch(n16 pc) -> n8 {
  n24 address = pc;
  if(pc.bit(15)) address |= CB << 15;
  return read(address);
}

auto S1C88::disassembleInstruction() -> string {
  n8 opcode = disassembleFetch(PC);
  string s;
  if(opcode == 0xce) {
    opcode = disassembleFetch(PC + 1);
    s.append(disassembleInstructionCE(opcode));
  } else if(opcode == 0xcf) {
    opcode = disassembleFetch(PC + 1);
    s.append(disassembleInstructionCF(opcode));
  } else {
    s.append(disassembleInstruction(opcode));
  }

  return pad(s, -20);
}


#define op(id, name, ...) case id: return {name, " ", vector<string>{__VA_ARGS__}.merge(",")};
//todo: macro-ify the strings used here
//todo: also make signed values display as such
//todo: also fix some immediate values having incorrect brackets
//todo: also modes that have an immediate after a BRn term are messed up here

auto S1C88::disassembleInstruction(n8 opcode) -> string {
  string n = {"[", hex(disassembleFetch(PC + 1), 2L), "]"};
  string nn = {"[", hex(disassembleFetch(PC + 1) | disassembleFetch(PC + 2) << 8, 4L), "]"};
  string BRn = {"[BR:", hex(disassembleFetch(PC + 1), 2L), "]"};
  switch(opcode) {
  op(0x00, "add", "A", "A");
  op(0x01, "add", "A", "B");
  op(0x02, "add", "A", n);
  op(0x10, "sub", "A", "A");
  op(0x11, "sub", "A", "B");
  op(0x12, "sub", "A", n);
  op(0x20, "and", "A", "A");
  op(0x21, "and", "A", "B");
  op(0x22, "and", "A", n);
  op(0x23, "and", "A", "[HL]");
  op(0x26, "and", "A", "[IX]");
  op(0x27, "and", "A", "[IY]");
  op(0x28, "or", "A", "A");
  op(0x29, "or", "A", "B");
  op(0x2a, "or", "A", n);
  op(0x2b, "or", "A", "[HL]");
  op(0x2e, "or", "A", "[IX]");
  op(0x2f, "or", "A", "[IY]");
  op(0x30, "cp", "A", "A");
  op(0x31, "cp", "A", "B");
  op(0x32, "cp", "A", n);
  op(0x33, "cp", "A", "[HL]");
  op(0x36, "cp", "A", "[IX]");
  op(0x37, "cp", "A", "[IY]");
  op(0x38, "xor", "A", "A");
  op(0x39, "xor", "A", "B");
  op(0x3a, "xor", "A", n);
  op(0x40, "ld", "A", "A");
  op(0x41, "ld", "A", "B");
  op(0x42, "ld", "A", "L");
  op(0x43, "ld", "A", "H");
  op(0x44, "ld", "A", BRn);
  op(0x45, "ld", "A", "[HL]");
  op(0x46, "ld", "A", "[IX]");
  op(0x47, "ld", "A", "[IY]");
  op(0x48, "ld", "B", "A");
  op(0x49, "ld", "B", "B");
  op(0x4a, "ld", "B", "L");
  op(0x4b, "ld", "B", "H");
  op(0x4c, "ld", "B", BRn);
  op(0x4d, "ld", "B", "[HL]");
  op(0x4e, "ld", "B", "[IX]");
  op(0x4f, "ld", "B", "[IY]");
  op(0x50, "ld", "L", "A");
  op(0x51, "ld", "L", "B");
  op(0x52, "ld", "L", "L");
  op(0x53, "ld", "L", "H");
  op(0x54, "ld", "L", BRn);
  op(0x55, "ld", "L", "[HL]");
  op(0x56, "ld", "L", "[IX]");
  op(0x57, "ld", "L", "[IY]");
  op(0x58, "ld", "H", "A");
  op(0x59, "ld", "H", "B");
  op(0x5a, "ld", "H", "L");
  op(0x5b, "ld", "H", "H");
  op(0x5c, "ld", "H", BRn);
  op(0x5d, "ld", "H", "[HL]");
  op(0x5e, "ld", "H", "[IX]");
  op(0x5f, "ld", "H", "[IY]");
  op(0x60, "ld", "[IX]", "A");
  op(0x61, "ld", "[IX]", "B");
  op(0x62, "ld", "[IX]", "L");
  op(0x63, "ld", "[IX]", "H");
  op(0x65, "ld", "[IX]", "[HL]");
  op(0x66, "ld", "[IX]", "[IX]");
  op(0x67, "ld", "[IX]", "[IY]");
  op(0x68, "ld", "[HL]", "A");
  op(0x69, "ld", "[HL]", "B");
  op(0x6a, "ld", "[HL]", "L");
  op(0x6b, "ld", "[HL]", "H");
  op(0x6d, "ld", "[HL]", "[HL]");
  op(0x6e, "ld", "[HL]", "[IX]");
  op(0x6f, "ld", "[HL]", "[IY]");
  op(0x70, "ld", "[IY]", "A");
  op(0x71, "ld", "[IY]", "B");
  op(0x72, "ld", "[IY]", "L");
  op(0x73, "ld", "[IY]", "H");
  op(0x75, "ld", "[IY]", "[HL]");
  op(0x76, "ld", "[IY]", "[IX]");
  op(0x77, "ld", "[IY]", "[IY]");
  op(0x78, "ld", BRn, "A");
  op(0x79, "ld", BRn, "B");
  op(0x7a, "ld", BRn, "L");
  op(0x7b, "ld", BRn, "H");
  op(0x7d, "ld", BRn, "[HL]");
  op(0x7e, "ld", BRn, "[IX]");
  op(0x7f, "ld", BRn, "[IY]");
  op(0x80, "inc", "A");
  op(0x81, "inc", "B");
  op(0x82, "inc", "L");
  op(0x83, "inc", "H");
  op(0x84, "inc", "BR");
  op(0x86, "inc", "[HL]");
  op(0x87, "inc", "SP");
  op(0x88, "dec", "A");
  op(0x89, "dec", "B");
  op(0x8a, "dec", "L");
  op(0x8b, "dec", "H");
  op(0x8c, "dec", "BR");
  op(0x8f, "dec", "SP");
  op(0x90, "inc", "BA");
  op(0x91, "inc", "HL");
  op(0x92, "inc", "IX");
  op(0x93, "inc", "IY");
  op(0x96, "bit", "A", n);
  op(0x97, "bit", "B", n);
  op(0x98, "dec", "BA");
  op(0x99, "dec", "HL");
  op(0x9a, "dec", "IX");
  op(0x9b, "dec", "IY");
  op(0x9c, "and", "SC", n);
  op(0x9d, "or", "SC", n);
  op(0x9e, "xor", "SC", n);
  op(0x9f, "ld", "SC", n);
  op(0xa0, "push", "BA");
  op(0xa1, "push", "HL");
  op(0xa2, "push", "IX");
  op(0xa3, "push", "IY");
  op(0xa4, "push", "BR");
  op(0xa5, "push", "EP");
  op(0xa6, "push", "IP");
  op(0xa7, "push", "SC");
  op(0xa8, "pop", "BA");
  op(0xa9, "pop", "HL");
  op(0xaa, "pop", "IX");
  op(0xab, "pop", "IY");
  op(0xac, "pop", "BR");
  op(0xad, "pop", "EP");
  op(0xae, "pop", "IP");
  op(0xaf, "pop", "SC");
  op(0xb0, "ld", "A", n);
  op(0xb1, "ld", "B", n);
  op(0xb2, "ld", "L", n);
  op(0xb3, "ld", "H", n);
  op(0xb4, "ld", "BR", n);
  op(0xb5, "ld", "[HL]", n);
  op(0xb6, "ld", "[IX]", n);
  op(0xb7, "ld", "[IY]", n);
  op(0xb8, "ld", "BA", nn);
  op(0xb9, "ld", "HL", nn);
  op(0xba, "ld", "IX", nn);
  op(0xbb, "ld", "IY", nn);
  op(0xbc, "ld", nn, "BA");
  op(0xbd, "ld", nn, "HL");
  op(0xbe, "ld", nn, "IX");
  op(0xbf, "ld", nn, "IY");
  op(0xc0, "add", "BA", nn);
  op(0xc1, "add", "HL", nn);
  op(0xc2, "add", "IX", nn);
  op(0xc3, "add", "IY", nn);
  op(0xc4, "ld", "BA", nn);
  op(0xc5, "ld", "HL", nn);
  op(0xc6, "ld", "IX", nn);
  op(0xc7, "ld", "IY", nn);
  op(0xc8, "ex", "BA", "HL");
  op(0xc9, "ex", "BA", "IX");
  op(0xca, "ex", "BA", "IY");
  op(0xcb, "ex", "BA", "SP");
  op(0xcc, "ex", "A", "B");
  op(0xcd, "ex", "A", "[HL]");
  op(0xd0, "sub", "BA", nn);
  op(0xd1, "sub", "HL", nn);
  op(0xd2, "sub", "IX", nn);
  op(0xd3, "sub", "IY", nn);
  op(0xd4, "cp", "BA", nn);
  op(0xd5, "cp", "HL", nn);
  op(0xd6, "cp", "IX", nn);
  op(0xd7, "cp", "IY", nn);
  op(0xd8, "and", BRn, n);
  op(0xd9, "or", BRn, n);
  op(0xdc, "bit", BRn, n);
  op(0xdd, "ld", BRn, n);
  op(0xe4, "jrs", "C", n);
  op(0xe5, "jrs", "NC", n);
  op(0xe6, "jrs", "Z", n);
  op(0xe7, "jrs", "NZ", n);
  op(0xec, "jrl", "C", nn);
  op(0xed, "jrl", "NC", nn);
  op(0xee, "jrl", "Z", nn);
  op(0xef, "jrl", "NZ", nn);
  op(0xf1, "jrs", n);
  op(0xf2, "carl", nn);
  op(0xf3, "jrl", nn);
  op(0xf5, "djr", "NZ", n);
  op(0xf8, "ret");
  op(0xff, "nop");
  default: running = false; return { hex(opcode, 2L), " (UNKNOWN) "};
  }
  unreachable;
}

auto S1C88::disassembleInstructionCE(n8 opcode) -> string {
  string n = {"[", hex(disassembleFetch(PC + 2), 2L), "]"};
  string nn = {"[", hex(disassembleFetch(PC + 2) | disassembleFetch(PC + 3) << 8, 4L), "]"};
  string BRn = {"[BR:", hex(disassembleFetch(PC + 2), 2L), "]"};
  switch(opcode) {
  op(0x00, "add", "A", "IX", n);
  op(0x01, "add", "A", "IY", n);
  op(0x05, "add", "[HL]", n);
  op(0x20, "and", "A", "IX", n);
  op(0x21, "and", "A", "IY", n);
  op(0x2c, "or", "[HL]", "A");
  op(0x2e, "or", "[HL]", "[IX]");
  op(0x2f, "or", "[HL]", "[IY]");
  op(0x35, "cp", "[HL]", n);
  op(0x40, "ld", "A", "IX", n);
  op(0x41, "ld", "A", "IY", n);
  op(0x42, "ld", "A", "IX", "L");
  op(0x43, "ld", "A", "IY", "L");
  op(0x44, "ld", "IX", "A");
  op(0x45, "ld", "IY", "A");
  op(0x46, "ld", "IX", "L", "A");
  op(0x47, "ld", "IY", "L", "A");
  op(0x48, "ld", "B", "IX", n);
  op(0x49, "ld", "B", "IY", n);
  op(0x4a, "ld", "B", "IX", "L");
  op(0x4b, "ld", "B", "IY", "L");
  op(0x4c, "ld", "IX", "B");
  op(0x4d, "ld", "IY", "B");
  op(0x4e, "ld", "IX", "L", "B");
  op(0x4f, "ld", "IY", "L", "B");
  op(0x50, "ld", "L", "IX", n);
  op(0x51, "ld", "L", "IY", n);
  op(0x52, "ld", "L", "IX", "L");
  op(0x53, "ld", "L", "IY", "L");
  op(0x54, "ld", "IX", "L");
  op(0x55, "ld", "IY", "L");
  op(0x56, "ld", "IX", "L", "L");
  op(0x57, "ld", "IY", "L", "L");
  op(0x58, "ld", "H", "IX", n);
  op(0x59, "ld", "H", "IY", n);
  op(0x5a, "ld", "H", "IX", "L");
  op(0x5b, "ld", "H", "IY", "L");
  op(0x5c, "ld", "IX", "H");
  op(0x5d, "ld", "IY", "H");
  op(0x5e, "ld", "IX", "L", "H");
  op(0x5f, "ld", "IY", "L", "H");
  op(0x84, "sll", "A");
  op(0x85, "sll", "B");
  op(0x88, "sra", "A");
  op(0x89, "sra", "B");
  op(0x8c, "srl", "A");
  op(0x8d, "srl", "B");
  op(0x90, "rl", "A");
  op(0x91, "rl", "B");
  op(0x93, "rl", "[HL]");
  op(0x94, "rlc", "A");
  op(0x95, "rlc", "B");
  op(0x9c, "rrc", "A");
  op(0x9d, "rrc", "B");
  op(0xa0, "cpl", "A");
  op(0xa1, "cpl", "B");
  op(0xa4, "neg", "A");
  op(0xa5, "neg", "B");
  op(0xa8, "sep");
  op(0xb0, "and", "B", n);
  op(0xb1, "and", "L", n);
  op(0xb2, "and", "H", n);
  op(0xb4, "or", "B", n);
  op(0xb5, "or", "L", n);
  op(0xb6, "or", "H", n);
  op(0xb8, "xor", "B", n);
  op(0xb9, "xor", "L", n);
  op(0xba, "xor", "H", n);
  op(0xbc, "cp", "B", n);
  op(0xbd, "cp", "L", n);
  op(0xbe, "cp", "H", n);
  op(0xbf, "cp", "BR", n);
  op(0xc0, "ld", "A", "BR");
  op(0xc1, "ld", "A", "SC");
  op(0xc2, "ld", "BR", "A");
  op(0xc3, "ld", "SC", "A");
  op(0xc4, "ld", "NB", n);
  op(0xc5, "ld", "EP", n);
  op(0xc6, "ld", "XP", n);
  op(0xc7, "ld", "YP", n);
  op(0xc8, "ld", "A", "NB");
  op(0xc9, "ld", "A", "EP");
  op(0xca, "ld", "A", "XP");
  op(0xcb, "ld", "A", "YP");
  op(0xcc, "ld", "NB", "A");
  op(0xcd, "ld", "EP", "A");
  op(0xce, "ld", "XP", "A");
  op(0xcf, "ld", "YP", "A");
  op(0xd0, "ld", "A", nn);
  op(0xd1, "ld", "B", nn);
  op(0xd2, "ld", "L", nn);
  op(0xd3, "ld", "H", nn);
  op(0xd4, "ld", nn, "A");
  op(0xd5, "ld", nn, "B");
  op(0xd6, "ld", nn, "H");
  op(0xd7, "ld", nn, "L");
  op(0xd8, "mlt");
  op(0xe0, "jrs", "LT", n);
  op(0xe1, "jrs", "LE", n);
  op(0xe2, "jrs", "GT", n);
  op(0xe3, "jrs", "GE", n);
  op(0xe4, "jrs", "V");
  op(0xe5, "jrs", "NV");
  op(0xe6, "jrs", "P");
  op(0xe7, "jrs", "M");
  op(0xe8, "jrs", "F0");
  op(0xe9, "jrs", "F1");
  op(0xea, "jrs", "F2");
  op(0xeb, "jrs", "F3");
  op(0xec, "jrs", "NF0");
  op(0xed, "jrs", "NF1");
  op(0xee, "jrs", "NF2");
  op(0xef, "jrs", "NF3");
  default: running = false; return { hex(0xce, 2L), " ", hex(opcode, 2L), " (UNKNOWN) "};
  }
  unreachable;
}

auto S1C88::disassembleInstructionCF(n8 opcode) -> string {
  string n = {"[", hex(disassembleFetch(PC + 2), 2L), "]"};
  string nn = {"[", hex(disassembleFetch(PC + 2) | disassembleFetch(PC + 3) << 8, 4L), "]"};
  string BRn = {"[BR:", hex(disassembleFetch(PC + 2), 2L), "]"};
  switch(opcode) {
  op(0x00, "add", "BA", "BA");
  op(0x01, "add", "BA", "HL");
  op(0x02, "add", "BA", "IX");
  op(0x03, "add", "BA", "IY");
  op(0x08, "sub", "BA", "BA");
  op(0x09, "sub", "BA", "HL");
  op(0x0a, "sub", "BA", "IX");
  op(0x0b, "sub", "BA", "IY");
  op(0x0c, "sbc", "BA", "BA");
  op(0x0d, "sbc", "BA", "HL");
  op(0x0e, "sbc", "BA", "IX");
  op(0x0f, "sbc", "BA", "IY");
  op(0x18, "cp", "BA", "BA");
  op(0x19, "cp", "BA", "HL");
  op(0x1a, "cp", "BA", "IX");
  op(0x1b, "cp", "BA", "IY");
  op(0x20, "add", "HL", "BA");
  op(0x21, "add", "HL", "HL");
  op(0x22, "add", "HL", "IX");
  op(0x23, "add", "HL", "IY");
  op(0x28, "sub", "HL", "BA");
  op(0x29, "sub", "HL", "HL");
  op(0x2a, "sub", "HL", "IX");
  op(0x2b, "sub", "HL", "IY");
  op(0x2c, "sbc", "HL", "BA");
  op(0x2d, "sbc", "HL", "HL");
  op(0x2e, "sbc", "HL", "IX");
  op(0x2f, "sbc", "HL", "IY");
  op(0x38, "cp", "HL", "BA");
  op(0x39, "cp", "HL", "HL");
  op(0x3a, "cp", "HL", "IX");
  op(0x3b, "cp", "HL", "IY");
  op(0x40, "add", "IX", "BA");
  op(0x41, "add", "IX", "HL");
  op(0x42, "add", "IY", "BA");
  op(0x43, "add", "IY", "HL");
  op(0x44, "add", "SP", "BA");
  op(0x45, "add", "SP", "HL");
  op(0x48, "sub", "IX", "BA");
  op(0x49, "sub", "IX", "HL");
  op(0x4a, "sub", "IY", "BA");
  op(0x4b, "sub", "IY", "HL");
  op(0x4c, "sub", "SP", "BA");
  op(0x4d, "sub", "SP", "HL");
  op(0x5c, "cp", "SP", "BA");
  op(0x5d, "cp", "SP", "HL");
  op(0x60, "adc", "BA", nn);
  op(0x61, "adc", "HL", nn);
  op(0x68, "add", "SP", nn);
  op(0x6a, "sub", "SP", nn);
  op(0x6c, "cp", "SP", nn);
  op(0x6e, "ld", "SP", nn);
  op(0x70, "ld", "BA", "SP", n);
  op(0x71, "ld", "HL", "SP", n);
  op(0x72, "ld", "IX", "SP", n);
  op(0x73, "ld", "IY", "SP", n);
  op(0x74, "ld", "SP", n, "BA");
  op(0x75, "ld", "SP", n, "HL");
  op(0x76, "ld", "SP", n, "IX");
  op(0x77, "ld", "SP", n, "IY");
  op(0xb0, "push", "A");
  op(0xb1, "push", "B");
  op(0xb2, "push", "L");
  op(0xb3, "push", "H");
  op(0xb4, "pop", "A");
  op(0xb5, "pop", "B");
  op(0xb6, "pop", "L");
  op(0xb7, "pop", "H");
  op(0xb8, "push", "all");
  op(0xb9, "push", "ale");
  op(0xbc, "pop", "all");
  op(0xc0, "ld", "[BA]", "[HL]");
  op(0xc1, "ld", "[HL]", "[HL]");
  op(0xc2, "ld", "[IX]", "[HL]");
  op(0xc3, "ld", "[IY]", "[HL]");
  op(0xc4, "ld", "[HL]", "BA");
  op(0xc5, "ld", "[HL]", "HL");
  op(0xc6, "ld", "[HL]", "IX");
  op(0xc7, "ld", "[HL]", "IY");
  op(0xd0, "ld", "[BA]", "[IX]");
  op(0xd1, "ld", "[HL]", "[IX]");
  op(0xd2, "ld", "[IX]", "[IX]");
  op(0xd3, "ld", "[IY]", "[IX]");
  op(0xd4, "ld", "[IX]", "BA");
  op(0xd5, "ld", "[IX]", "HL");
  op(0xd6, "ld", "[IX]", "IX");
  op(0xd7, "ld", "[IX]", "IY");
  op(0xd8, "ld", "[BA]", "[IY]");
  op(0xd9, "ld", "[HL]", "[IY]");
  op(0xda, "ld", "[IX]", "[IY]");
  op(0xdb, "ld", "[IY]", "[IY]");
  op(0xdc, "ld", "[IY]", "BA");
  op(0xdd, "ld", "[IY]", "HL");
  op(0xde, "ld", "[IY]", "IX");
  op(0xdf, "ld", "[IY]", "IY");
  op(0xe0, "ld", "BA", "BA");
  op(0xe1, "ld", "BA", "HL");
  op(0xe2, "ld", "BA", "IX");
  op(0xe3, "ld", "BA", "IY");
  op(0xe4, "ld", "HL", "BA");
  op(0xe5, "ld", "HL", "HL");
  op(0xe6, "ld", "HL", "IX");
  op(0xe7, "ld", "HL", "IY");
  op(0xe8, "ld", "IX", "BA");
  op(0xe9, "ld", "IX", "HL");
  op(0xea, "ld", "IX", "IX");
  op(0xeb, "ld", "IX", "IY");
  op(0xec, "ld", "IY", "BA");
  op(0xed, "ld", "IY", "HL");
  op(0xee, "ld", "IY", "IX");
  op(0xef, "ld", "IY", "IY");
  op(0xf0, "ld", "SP", "BA");
  op(0xf1, "ld", "SP", "HL");
  op(0xf2, "ld", "SP", "IX");
  op(0xf3, "ld", "SP", "IY");
  op(0xf4, "ld", "HL", "SP");
  op(0xf5, "ld", "HL", "PC");
  op(0xf8, "ld", "BA", "SP");
  op(0xf9, "ld", "SP", "PC");
  op(0xfa, "ld", "IX", "SP");
  op(0xfe, "ld", "IY", "SP");
  default: running = false; return { hex(0xcf, 2L), " ", hex(opcode, 2L), " (UNKNOWN) "};
  }
  unreachable;
}

#undef op

auto S1C88::disassembleContext() -> string {
  string s0;
  s0.append("BA:", hex(BA, 4L), " ");
  s0.append("HL:", hex(HL, 4L), " ");
  s0.append("IX:", hex(IX, 4L), " ");
  s0.append("IY:", hex(IY, 4L), " ");
  s0.append("PC:", hex(PC, 4L), " ");
  s0.append("SP:", hex(SP, 4L), " ");
  s0.append("BR:", hex(BR, 2L), " ");
  s0.append("SC:", hex(SC, 2L), " ");

  string s1;
  s1 = pad("", -20);
  s1.append("NB:", hex(NB, 2L), " ");
  s1.append("CB:", hex(CB, 2L), " ");
  s1.append("EP:", hex(EP, 2L), " ");
  s1.append("XP:", hex(XP, 2L), " ");
  s1.append("YP:", hex(YP, 2L), " ");

  return {s0, "\n", s1};
}
